apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: burstable-vpa
  namespace: qos
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: burstable-app
  updatePolicy:
    updateMode: "Off"
