apiVersion: apps/v1
kind: Deployment
metadata:
  name: best-effort-app
  namespace: qos
  labels:
    app: best-effort
spec:
  replicas: 1
  selector:
    matchLabels:
      app: best-effort
  template:
    metadata:
      labels:
        app: best-effort
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["sleep"]
          args: ["3600"]
