apiVersion: apps/v1
kind: Deployment
metadata:
  name: burstable-app
  namespace: qos
  labels:
    app: burstable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: burstable
  template:
    metadata:
      labels:
        app: burstable
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["sleep"]
          args: ["3600"]
          resources:
            requests:
              cpu: "100m"
              memory: "100M"
            limits:
              cpu: "250m"
              memory: "600M"
