apiVersion: apps/v1
kind: Deployment
metadata:
  name: guaranteed-app
  namespace: qos
  labels:
    app: guaranteed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guaranteed
  template:
    metadata:
      labels:
        app: guaranteed
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["sleep"]
          args: ["3600"]
          resources:
            requests:
              cpu: "250m"
              memory: "600M"
            limits:
              cpu: "250m"
              memory: "600M"
