apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-generator-app
  namespace: qos
  labels:
    app: traffic-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-generator
  template:
    metadata:
      labels:
        app: traffic-generator
    spec:
      containers:
        - name: sleep-container
          image: polinux/stress
          command: ["sleep"]
          args: ["3600"]
          resources:
            limits:
              cpu: "250m"
              memory: "600M"
